import { FileText, Clock, TrendingUp, ExternalLink, Download, File } from 'lucide-react';
import { ScrapeData } from '../lib/supabase';

interface ResultsDisplayProps {
  data: ScrapeData;
}

// Helper function to clean markdown and HTML from text
function cleanHighlightText(text: string): string {
  if (!text) return '';
  
  // Remove markdown image syntax: ![alt](url)
  let cleaned = text.replace(/!\[([^\]]*)\]\([^\)]+\)/g, '$1');
  
  // Remove markdown link syntax: [text](url)
  cleaned = cleaned.replace(/\[([^\]]+)\]\([^\)]+\)/g, '$1');
  
  // Remove HTML tags
  cleaned = cleaned.replace(/<[^>]+>/g, '');
  
  // Remove excessive whitespace
  cleaned = cleaned.replace(/\s+/g, ' ').trim();
  
  // If it's still too short or looks like a URL/code, return empty
  if (cleaned.length < 10 || cleaned.includes('http') || cleaned.startsWith('!')) {
    return '';
  }
  
  return cleaned;
}

// Helper to escape HTML for safe rendering
function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

export default function ResultsDisplay({ data }: ResultsDisplayProps) {
  
  const exportAnalysis = (format: string) => {
    const content = `
AI RESEARCH & ANALYSIS REPORT
${'='.repeat(50)}

Title: ${data.title}
URL: ${data.url}
Keywords: ${data.keywords?.join(', ') || 'None'}
Date: ${data.created_at ? new Date(data.created_at).toLocaleString() : 'N/A'}

${'='.repeat(50)}

SOURCE SUMMARY
${'-'.repeat(50)}
${data.meta_description || 'No description available'}

${'='.repeat(50)}

VERIFIED ORIGIN / MOMENT OF TRUTH
${'-'.repeat(50)}
${data.verified_origin || 'Historical analysis not available'}

${'='.repeat(50)}

LATEST UPDATES & FUTURE FORECAST
${'-'.repeat(50)}
${data.future_forecast || 'Future forecast not available'}

${'='.repeat(50)}

AI SUMMARY
${'-'.repeat(50)}
${data.ai_summary || 'No AI summary available'}

${'='.repeat(50)}

KEY HIGHLIGHTS
${'-'.repeat(50)}
${data.highlighted_content?.map((item, i) => `${i + 1}. ${cleanHighlightText(item.text)}`).filter(text => text.length > 3).join('\n') || 'No highlights available'}

${'='.repeat(50)}

RAW CONTENT (First 2000 characters)
${'-'.repeat(50)}
${data.raw_content?.substring(0, 2000) || 'No content available'}...

${'='.repeat(50)}
Generated by ScrapeMaster - AI Research & Analysis Platform
`;

    let blob: Blob;
    let filename: string;

    switch (format) {
      case 'txt':
        blob = new Blob([content], { type: 'text/plain' });
        filename = `analysis_${Date.now()}.txt`;
        break;
      case 'doc':
        blob = new Blob([content], { type: 'application/msword' });
        filename = `analysis_${Date.now()}.doc`;
        break;
      case 'json':
        blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        filename = `analysis_${Date.now()}.json`;
        break;
      case 'pdf':
        // FIXED: Improved PDF generation with proper content loading
        const printWindow = window.open('', '_blank');
        if (printWindow) {
          const cleanedHighlights = data.highlighted_content
            ?.map(item => cleanHighlightText(item.text))
            .filter(text => text.length > 10) || [];

          printWindow.document.write(`
            <!DOCTYPE html>
            <html>
              <head>
                <title>${escapeHtml(data.title || 'Analysis Report')}</title>
                <meta charset="UTF-8">
                <style>
                  * { margin: 0; padding: 0; box-sizing: border-box; }
                  body { 
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
                    padding: 40px; 
                    line-height: 1.6;
                    color: #333;
                    background: white;
                  }
                  h1 { 
                    color: #7c3aed; 
                    border-bottom: 3px solid #7c3aed; 
                    padding-bottom: 10px;
                    margin-bottom: 20px;
                    font-size: 28px;
                  }
                  h2 { 
                    color: #2563eb; 
                    margin-top: 30px;
                    margin-bottom: 15px;
                    font-size: 20px;
                  }
                  .section { 
                    margin: 20px 0; 
                    padding: 15px; 
                    background: #f9fafb; 
                    border-left: 4px solid #7c3aed;
                    page-break-inside: avoid;
                  }
                  .meta { 
                    color: #666; 
                    font-size: 14px; 
                    margin: 8px 0;
                    line-height: 1.8;
                  }
                  .keyword { 
                    display: inline-block; 
                    background: #e0e7ff; 
                    padding: 4px 12px; 
                    margin: 4px; 
                    border-radius: 12px;
                    font-size: 12px;
                  }
                  .highlight-item {
                    margin: 10px 0;
                    padding: 10px;
                    background: white;
                    border-left: 3px solid #a855f7;
                  }
                  .footer {
                    margin-top: 40px;
                    padding-top: 20px;
                    border-top: 2px solid #e5e7eb;
                    text-align: center;
                    color: #9ca3af;
                    font-size: 12px;
                  }
                  @media print {
                    body { padding: 20px; }
                    .section { page-break-inside: avoid; }
                  }
                </style>
              </head>
              <body>
                <h1>AI Research & Analysis Report</h1>
                
                <div class="meta"><strong>Title:</strong> ${escapeHtml(data.title || 'Untitled')}</div>
                <div class="meta"><strong>URL:</strong> ${escapeHtml(data.url)}</div>
                <div class="meta"><strong>Date:</strong> ${data.created_at ? new Date(data.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
                
                ${data.keywords && data.keywords.length > 0 ? `
                  <div class="meta">
                    <strong>Keywords:</strong> 
                    ${data.keywords.map(k => `<span class="keyword">${escapeHtml(k)}</span>`).join('')}
                  </div>
                ` : ''}
                
                <div class="section">
                  <h2>Source Summary</h2>
                  <p>${escapeHtml(data.meta_description || 'No summary available').replace(/\n/g, '<br>')}</p>
                </div>
                
                ${data.verified_origin ? `
                  <div class="section">
                    <h2>Verified Origin / Moment of Truth</h2>
                    <p>${escapeHtml(data.verified_origin).replace(/\n/g, '<br>')}</p>
                  </div>
                ` : ''}
                
                ${data.future_forecast ? `
                  <div class="section">
                    <h2>Latest Updates & Future Forecast</h2>
                    <p>${escapeHtml(data.future_forecast).replace(/\n/g, '<br>')}</p>
                  </div>
                ` : ''}
                
                ${data.ai_summary ? `
                  <div class="section">
                    <h2>AI Summary</h2>
                    <p>${escapeHtml(data.ai_summary)}</p>
                  </div>
                ` : ''}
                
                ${cleanedHighlights.length > 0 ? `
                  <div class="section">
                    <h2>Key Highlights</h2>
                    ${cleanedHighlights.map((text, i) => `
                      <div class="highlight-item">
                        <strong>${i + 1}.</strong> ${escapeHtml(text)}
                      </div>
                    `).join('')}
                  </div>
                ` : ''}
                
                <div class="footer">
                  Generated by ScrapeMaster - AI Research & Analysis Platform<br>
                  Report generated on ${new Date().toLocaleString()}
                </div>
              </body>
            </html>
          `);
          
          printWindow.document.close();
          
          // FIXED: Wait for content to fully load before printing
          printWindow.onload = function() {
            setTimeout(() => {
              printWindow.focus();
              printWindow.print();
            }, 1000); // Increased timeout to 1 second
          };
          
          // Fallback if onload doesn't fire
          setTimeout(() => {
            if (printWindow && !printWindow.closed) {
              printWindow.focus();
              printWindow.print();
            }
          }, 1500);
        }
        return;
      default:
        return;
    }

    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Page Information Card */}
      <div className="bg-gray-800/30 rounded-xl p-6 border border-purple-500/20">
        <h3 className="text-xl font-bold text-white mb-4 flex items-center space-x-2">
          <FileText className="w-5 h-5 text-purple-400" />
          <span>Page Information</span>
        </h3>

        <div className="space-y-3">
          <div>
            <label className="text-sm text-purple-300 font-medium">Title</label>
            <p className="text-white mt-1">{data.title || 'No title found'}</p>
          </div>

          {data.meta_description && (
            <div>
              <label className="text-sm text-purple-300 font-medium">Meta Description</label>
              <p className="text-gray-300 mt-1 text-sm">{data.meta_description}</p>
            </div>
          )}

          {data.keywords && data.keywords.length > 0 && (
            <div>
              <label className="text-sm text-purple-300 font-medium">Keywords Used</label>
              <div className="flex flex-wrap gap-2 mt-2">
                {data.keywords.map((keyword, i) => (
                  <span
                    key={i}
                    className="px-3 py-1 bg-purple-500/20 text-purple-300 text-sm rounded-full border border-purple-500/30"
                  >
                    {keyword}
                  </span>
                ))}
              </div>
            </div>
          )}

          <div>
            <label className="text-sm text-purple-300 font-medium">URL</label>
            <a
              href={data.url}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center space-x-1 text-blue-400 hover:text-blue-300 mt-1 text-sm group"
            >
              <span className="break-all">{data.url}</span>
              <ExternalLink className="w-4 h-4 flex-shrink-0 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform" />
            </a>
          </div>
        </div>
      </div>

      {/* Source Summary Section */}
      <div className="bg-green-900/20 rounded-xl p-6 border border-green-500/30">
        <div className="flex items-center space-x-3 mb-4">
          <div className="w-10 h-10 bg-green-500/20 rounded-lg flex items-center justify-center">
            <FileText className="w-5 h-5 text-green-400" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-white">Source Summary</h3>
            <p className="text-sm text-gray-400">What the input URL is conveying</p>
          </div>
        </div>
        <div className="text-gray-300 leading-relaxed whitespace-pre-line">
          {data.meta_description || data.ai_summary || 'No summary available'}
        </div>
      </div>

      {/* Verified Origin / Moment of Truth */}
      {data.verified_origin && (
        <div className="bg-orange-900/20 rounded-xl p-6 border border-orange-500/30">
          <div className="flex items-center space-x-3 mb-4">
            <div className="w-10 h-10 bg-orange-500/20 rounded-lg flex items-center justify-center">
              <Clock className="w-5 h-5 text-orange-400" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">Verified Origin / Moment of Truth</h3>
              <p className="text-sm text-gray-400">Historical analysis and earliest mentions</p>
            </div>
          </div>
          <div className="space-y-3 text-gray-300 leading-relaxed whitespace-pre-line">
            {data.verified_origin}
          </div>
        </div>
      )}

      {/* Latest Updates & Future Forecast */}
      {data.future_forecast && (
        <div className="bg-blue-900/20 rounded-xl p-6 border border-blue-500/30">
          <div className="flex items-center space-x-3 mb-4">
            <div className="w-10 h-10 bg-blue-500/20 rounded-lg flex items-center justify-center">
              <TrendingUp className="w-5 h-5 text-blue-400" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">Latest Updates & Future Forecast</h3>
              <p className="text-sm text-gray-400">Current trends and future predictions</p>
            </div>
          </div>
          <div className="space-y-3 text-gray-300 leading-relaxed whitespace-pre-line">
            {data.future_forecast}
          </div>
        </div>
      )}

      {/* AI Summary */}
      {data.ai_summary && (
        <div className="bg-purple-900/20 rounded-xl p-6 border border-purple-500/30">
          <h3 className="text-lg font-bold text-white mb-3">AI Summary</h3>
          <p className="text-gray-300 leading-relaxed">{data.ai_summary}</p>
        </div>
      )}

      {/* Key Highlights */}
      {data.highlighted_content && data.highlighted_content.length > 0 && (
        <div className="bg-gray-800/30 rounded-xl p-6 border border-purple-500/20">
          <h3 className="text-lg font-bold text-white mb-4">Key Highlights</h3>
          <div className="space-y-3">
            {data.highlighted_content
              .map(item => ({
                ...item,
                text: cleanHighlightText(item.text)
              }))
              .filter(item => item.text.length > 0)
              .map((item, index) => (
                <div
                  key={index}
                  className="flex items-start space-x-3 p-3 bg-gray-900/50 rounded-lg border border-purple-500/20"
                >
                  <div className="flex-shrink-0 w-6 h-6 bg-purple-500/30 rounded-full flex items-center justify-center text-purple-300 text-xs font-bold">
                    {item.importance || index + 1}
                  </div>
                  <p className="text-gray-300 text-sm flex-1">{item.text}</p>
                </div>
              ))}
          </div>
          {data.highlighted_content.filter(item => cleanHighlightText(item.text).length > 0).length === 0 && (
            <p className="text-gray-500 text-sm text-center py-4">
              No key highlights extracted. Try different keywords or check the AI Summary section.
            </p>
          )}
        </div>
      )}

      {/* Open Graph Data */}
      {data.og_data && (
        <div className="bg-gray-800/30 rounded-xl p-6 border border-purple-500/20">
          <h3 className="text-lg font-bold text-white mb-4">Open Graph Data</h3>
          
          {data.og_data.image && (
            <div className="mb-4">
              <img
                src={data.og_data.image}
                alt={data.og_data.title || 'OG Image'}
                className="w-full h-48 object-cover rounded-lg"
                onError={(e) => {
                  e.currentTarget.style.display = 'none';
                }}
              />
            </div>
          )}

          <div className="space-y-2 text-sm">
            {data.og_data.title && (
              <div>
                <span className="text-purple-300 font-medium">OG Title: </span>
                <span className="text-gray-300">{data.og_data.title}</span>
              </div>
            )}
            {data.og_data.description && (
              <div>
                <span className="text-purple-300 font-medium">OG Description: </span>
                <span className="text-gray-300">{data.og_data.description}</span>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Links Found */}
      {data.links && data.links.length > 0 && (
        <div className="bg-gray-800/30 rounded-xl p-6 border border-purple-500/20">
          <h3 className="text-lg font-bold text-white mb-4">Links Found ({data.links.length})</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 max-h-64 overflow-y-auto">
            {data.links.slice(0, 20).map((link, index) => (
              <a
                key={index}
                href={link.url}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center space-x-2 p-3 bg-gray-900/50 rounded-lg hover:bg-gray-900/70 transition-colors border border-purple-500/10 hover:border-purple-500/30 group"
              >
                <ExternalLink className="w-4 h-4 text-purple-400 flex-shrink-0 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform" />
                <span className="text-sm text-gray-300 truncate">{link.text || link.url}</span>
                {link.type && (
                  <span className="text-xs text-purple-400 ml-auto">
                    {link.type}
                  </span>
                )}
              </a>
            ))}
          </div>
          {data.links.length > 20 && (
            <p className="text-sm text-gray-500 mt-3">
              Showing 20 of {data.links.length} links
            </p>
          )}
        </div>
      )}

      {/* Export Section */}
      <div className="bg-gray-800/30 rounded-xl p-6 border border-purple-500/20">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <h3 className="text-lg font-bold text-white mb-1 flex items-center gap-2">
              <Download className="w-5 h-5" />
              Export Analysis
            </h3>
            <p className="text-sm text-gray-400">Download this analysis in various formats</p>
          </div>
          <div className="flex gap-2 flex-wrap">
            <button
              onClick={() => exportAnalysis('txt')}
              className="px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded-lg transition-colors flex items-center gap-2 text-sm"
            >
              <File className="w-4 h-4" />
              .TXT
            </button>
            <button
              onClick={() => exportAnalysis('doc')}
              className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors flex items-center gap-2 text-sm"
            >
              <FileText className="w-4 h-4" />
              .DOC
            </button>
            <button
              onClick={() => exportAnalysis('pdf')}
              className="px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg transition-colors flex items-center gap-2 text-sm"
            >
              <Download className="w-4 h-4" />
              .PDF
            </button>
            <button
              onClick={() => exportAnalysis('json')}
              className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg transition-colors flex items-center gap-2 text-sm"
            >
              <File className="w-4 h-4" />
              .JSON
            </button>
          </div>
        </div>
      </div>

      {/* Timestamps */}
      {data.created_at && (
        <div className="text-center text-sm text-gray-500 pt-4 border-t border-gray-800">
          <div className="flex items-center justify-center gap-4">
            <span>Created: {new Date(data.created_at).toLocaleString()}</span>
            <span>•</span>
            <span>Completed: {new Date(data.created_at).toLocaleString()}</span>
          </div>
        </div>
      )}
    </div>
  );
}