import { FileText, Clock, TrendingUp, ExternalLink, Download, File, AlertTriangle, Copy, Check, Linkedin, Twitter, Instagram, Facebook, Share2 } from 'lucide-react';
import { ScrapeData } from '../lib/supabase';
import { useState } from 'react';

interface ResultsDisplayProps {
  data: ScrapeData;
}

// Helper function to clean markdown and HTML from text
function cleanHighlightText(text: string): string {
  if (!text) return '';
  
  // Remove markdown image syntax: ![alt](url)
  let cleaned = text.replace(/!\[([^\]]*)\]\([^\)]+\)/g, '$1');
  
  // Remove markdown link syntax: [text](url)
  cleaned = cleaned.replace(/\[([^\]]+)\]\([^\)]+\)/g, '$1');
  
  // Remove HTML tags
  cleaned = cleaned.replace(/<[^>]+>/g, '');
  
  // Remove excessive whitespace
  cleaned = cleaned.replace(/\s+/g, ' ').trim();
  
  // If it's still too short or looks like a URL/code, return empty
  if (cleaned.length < 10 || cleaned.includes('http') || cleaned.startsWith('!')) {
    return '';
  }
  
  return cleaned;
}

export default function ResultsDisplay({ data }: ResultsDisplayProps) {
  const [copiedField, setCopiedField] = useState<string | null>(null);

  const copyToClipboard = async (text: string, field: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedField(field);
      setTimeout(() => setCopiedField(null), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const shareToLinkedIn = () => {
    const text = data.linkedin_post || `Check out: ${data.title}`;
    const url = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(data.url)}`;
    window.open(url, '_blank', 'width=600,height=600');
  };

  const shareToTwitter = () => {
    const text = data.twitter_post || `${data.title} ${data.url}`;
    const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank', 'width=600,height=400');
  };

  const shareToFacebook = () => {
    const url = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(data.url)}`;
    window.open(url, '_blank', 'width=600,height=400');
  };

  const shareToInstagram = () => {
    copyToClipboard(data.instagram_caption || data.title || '', 'instagram-share');
    alert('Instagram caption copied! Open Instagram app to paste and share.');
  };

  const exportAnalysisJSON = () => {
    const jsonOutput = {
      url: data.url,
      key_highlights: data.key_highlights || [],
      summary: data.short_summary || data.ai_summary || data.meta_description || '',
      keyword_matches: data.keywords || [],
      keyword_relevance_score: data.keyword_relevance_score || null,
      social_media: {
        linkedin: data.linkedin_post || '',
        twitter: data.twitter_post || '',
        instagram: data.instagram_caption || '',
        facebook: data.facebook_post || ''
      }
    };

    const blob = new Blob([JSON.stringify(jsonOutput, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scrape_analysis_${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportAnalysis = (format: string) => {
    const content = `
AI RESEARCH & ANALYSIS REPORT
${'='.repeat(50)}

Title: ${data.title}
URL: ${data.url}
Keywords: ${data.keywords?.join(', ') || 'None'}
Date: ${data.created_at ? new Date(data.created_at).toLocaleString() : 'N/A'}

${'='.repeat(50)}

SOURCE SUMMARY
${'-'.repeat(50)}
${data.meta_description || 'No description available'}

${'='.repeat(50)}

VERIFIED ORIGIN / MOMENT OF TRUTH
${'-'.repeat(50)}
${data.verified_origin || 'Historical analysis not available'}

${'='.repeat(50)}

LATEST UPDATES & FUTURE FORECAST
${'-'.repeat(50)}
${data.future_forecast || 'Future forecast not available'}

${'='.repeat(50)}

AI SUMMARY
${'-'.repeat(50)}
${data.ai_summary || 'No AI summary available'}

${'='.repeat(50)}

KEY HIGHLIGHTS
${'-'.repeat(50)}
${data.highlighted_content?.map((item, i) => `${i + 1}. ${item.text}`).join('\n') || 'No highlights available'}

${'='.repeat(50)}

RAW CONTENT (First 2000 characters)
${'-'.repeat(50)}
${data.raw_content?.substring(0, 2000) || 'No content available'}...

${'='.repeat(50)}
Generated by ScrapeMaster - AI Research & Analysis Platform
`;

    let blob: Blob;
    let filename: string;

    switch (format) {
      case 'txt':
        blob = new Blob([content], { type: 'text/plain' });
        filename = `analysis_${Date.now()}.txt`;
        break;
      case 'doc':
        blob = new Blob([content], { type: 'application/msword' });
        filename = `analysis_${Date.now()}.doc`;
        break;
      case 'json':
        blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        filename = `analysis_${Date.now()}.json`;
        break;
      case 'pdf':
        // Simple PDF generation using print functionality
        const printWindow = window.open('', '_blank');
        if (printWindow) {
          printWindow.document.write(`
            <html>
              <head>
                <title>${data.title || 'Analysis Report'}</title>
                <style>
                  body { font-family: Arial, sans-serif; padding: 40px; line-height: 1.6; }
                  h1 { color: #7c3aed; border-bottom: 3px solid #7c3aed; padding-bottom: 10px; }
                  h2 { color: #2563eb; margin-top: 30px; }
                  .section { margin: 20px 0; padding: 15px; background: #f3f4f6; border-left: 4px solid #7c3aed; }
                  .meta { color: #666; font-size: 14px; margin: 10px 0; }
                  .keyword { display: inline-block; background: #e0e7ff; padding: 4px 12px; margin: 4px; border-radius: 12px; }
                </style>
              </head>
              <body>
                <h1>AI Research & Analysis Report</h1>
                <div class="meta"><strong>Title:</strong> ${data.title || 'Untitled'}</div>
                <div class="meta"><strong>URL:</strong> ${data.url}</div>
                <div class="meta"><strong>Date:</strong> ${data.created_at ? new Date(data.created_at).toLocaleDateString() : new Date().toLocaleDateString()}</div>
                ${data.keywords && data.keywords.length > 0 ? `
                  <div class="meta">
                    <strong>Keywords:</strong> 
                    ${data.keywords.map(k => `<span class="keyword">${k}</span>`).join('')}
                  </div>
                ` : ''}
                
                <div class="section">
                  <h2>Source Summary</h2>
                  <p>${(data.meta_description || 'No summary available').replace(/\n/g, '<br>')}</p>
                </div>
                
                ${data.verified_origin ? `
                  <div class="section">
                    <h2>Verified Origin / Moment of Truth</h2>
                    <p>${data.verified_origin.replace(/\n/g, '<br>')}</p>
                  </div>
                ` : ''}
                
                ${data.future_forecast ? `
                  <div class="section">
                    <h2>Latest Updates & Future Forecast</h2>
                    <p>${data.future_forecast.replace(/\n/g, '<br>')}</p>
                  </div>
                ` : ''}
                
                ${data.ai_summary ? `
                  <div class="section">
                    <h2>AI Summary</h2>
                    <p>${data.ai_summary}</p>
                  </div>
                ` : ''}
                
                ${data.highlighted_content && data.highlighted_content.length > 0 ? `
                  <div class="section">
                    <h2>Key Highlights</h2>
                    <ul>
                      ${data.highlighted_content.map(item => `<li>${item.text}</li>`).join('')}
                    </ul>
                  </div>
                ` : ''}
                
                <div class="meta" style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #ccc;">
                  Generated by ScrapeMaster - AI Research & Analysis Platform
                </div>
              </body>
            </html>
          `);
          printWindow.document.close();
          setTimeout(() => {
            printWindow.print();
          }, 500);
        }
        return;
      default:
        return;
    }

    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Check if keywords don't match the content
  const hasKeywordWarning = data.meta_description?.includes('No content found matching') ||
                            data.meta_description?.includes('⚠️') ||
                            data.verified_origin?.includes('does not contain content related to');

  return (
    <div className="space-y-6">
      {/* Keyword Mismatch Warning */}
      {hasKeywordWarning && data.keywords && data.keywords.length > 0 && (
        <div className="bg-yellow-900/20 border-2 border-yellow-500/50 rounded-xl p-6 animate-fade-in">
          <div className="flex items-start space-x-4">
            <div className="flex-shrink-0">
              <AlertTriangle className="w-8 h-8 text-yellow-400" />
            </div>
            <div className="flex-1">
              <h3 className="text-lg font-bold text-yellow-300 mb-2">
                No Keyword Matches Found
              </h3>
              <p className="text-yellow-100/90 mb-3">
                The scraped webpage does not contain content related to your keywords: <strong>{data.keywords.join(', ')}</strong>
              </p>
              <div className="bg-yellow-800/30 rounded-lg p-4 border border-yellow-500/30">
                <p className="text-sm text-yellow-200 mb-2">
                  <strong>Suggestions:</strong>
                </p>
                <ul className="text-sm text-yellow-100/80 space-y-1 list-disc list-inside">
                  <li>Verify that the URL contains information about "{data.keywords.join(', ')}"</li>
                  <li>Try using different or more general keywords</li>
                  <li>Check if the webpage URL is correct</li>
                  <li>Try searching for a different source that covers your topic</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Page Information Card */}
      <div className="bg-gray-800/30 rounded-xl p-6 border border-purple-500/20">
        <h3 className="text-xl font-bold text-white mb-4 flex items-center space-x-2">
          <FileText className="w-5 h-5 text-purple-400" />
          <span>Page Information</span>
        </h3>

        <div className="space-y-3">
          <div>
            <label className="text-sm text-purple-300 font-medium">Title</label>
            <p className="text-white mt-1">{data.title || 'No title found'}</p>
          </div>

          {data.meta_description && (
            <div>
              <label className="text-sm text-purple-300 font-medium">Meta Description</label>
              <p className="text-gray-300 mt-1 text-sm">{data.meta_description}</p>
            </div>
          )}

          {data.keywords && data.keywords.length > 0 && (
            <div>
              <label className="text-sm text-purple-300 font-medium">Keywords Used</label>
              <div className="flex flex-wrap gap-2 mt-2">
                {data.keywords.map((keyword, i) => (
                  <span
                    key={i}
                    className="px-3 py-1 bg-purple-500/20 text-purple-300 text-sm rounded-full border border-purple-500/30"
                  >
                    {keyword}
                  </span>
                ))}
              </div>
            </div>
          )}

          <div>
            <label className="text-sm text-purple-300 font-medium">URL</label>
            <a
              href={data.url}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center space-x-1 text-blue-400 hover:text-blue-300 mt-1 text-sm group"
            >
              <span className="break-all">{data.url}</span>
              <ExternalLink className="w-4 h-4 flex-shrink-0 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform" />
            </a>
          </div>
        </div>
      </div>

      {/* Keyword Relevance Score */}
      {data.keyword_relevance_score !== undefined && data.keywords && data.keywords.length > 0 && (
        <div className="bg-blue-900/20 rounded-xl p-6 border border-blue-500/30">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-blue-500/20 rounded-lg flex items-center justify-center">
                <TrendingUp className="w-5 h-5 text-blue-400" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-white">Keyword Relevance Score</h3>
                <p className="text-sm text-gray-400">Content match for: {data.keywords.join(', ')}</p>
              </div>
            </div>
            <div className="flex items-center space-x-2">
              <span className={`text-4xl font-bold ${
                data.keyword_relevance_score >= 7 ? 'text-green-400' :
                data.keyword_relevance_score >= 4 ? 'text-yellow-400' :
                'text-red-400'
              }`}>
                {data.keyword_relevance_score.toFixed(1)}
              </span>
              <span className="text-xl text-gray-400">/10</span>
            </div>
          </div>
          <div className="mt-4 w-full bg-gray-700 rounded-full h-3">
            <div
              className={`h-3 rounded-full ${
                data.keyword_relevance_score >= 7 ? 'bg-green-400' :
                data.keyword_relevance_score >= 4 ? 'bg-yellow-400' :
                'bg-red-400'
              }`}
              style={{ width: `${(data.keyword_relevance_score / 10) * 100}%` }}
            />
          </div>
        </div>
      )}

      {/* Short Summary */}
      {data.short_summary && (
        <div className="bg-indigo-900/20 rounded-xl p-6 border border-indigo-500/30">
          <div className="flex items-center space-x-3 mb-4">
            <div className="w-10 h-10 bg-indigo-500/20 rounded-lg flex items-center justify-center">
              <FileText className="w-5 h-5 text-indigo-400" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">Short Summary</h3>
              <p className="text-sm text-gray-400">Concise 150-word overview</p>
            </div>
          </div>
          <div className="text-gray-300 leading-relaxed">
            {data.short_summary}
          </div>
        </div>
      )}

      {/* Key Highlights */}
      {data.key_highlights && data.key_highlights.length > 0 && (
        <div className="bg-purple-900/20 rounded-xl p-6 border border-purple-500/30">
          <div className="flex items-center space-x-3 mb-4">
            <div className="w-10 h-10 bg-purple-500/20 rounded-lg flex items-center justify-center">
              <FileText className="w-5 h-5 text-purple-400" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">Key Highlights</h3>
              <p className="text-sm text-gray-400">Main takeaways from the content</p>
            </div>
          </div>
          <ul className="space-y-3">
            {data.key_highlights.map((highlight, index) => (
              <li key={index} className="flex items-start space-x-3 text-gray-300">
                <span className="flex-shrink-0 w-6 h-6 bg-purple-500/30 rounded-full flex items-center justify-center text-purple-300 text-xs font-bold mt-0.5">
                  {index + 1}
                </span>
                <span className="flex-1">{highlight}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Social Media Posts */}
      {(data.linkedin_post || data.twitter_post || data.instagram_caption || data.facebook_post) && (
        <div className="bg-gradient-to-br from-pink-900/20 to-purple-900/20 rounded-xl p-6 border border-pink-500/30">
          <div className="flex items-center justify-between flex-wrap gap-4 mb-6">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-pink-500/20 rounded-lg flex items-center justify-center">
                <Share2 className="w-5 h-5 text-pink-400" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-white">Social Media Posts</h3>
                <p className="text-sm text-gray-400">Ready-to-use content & share buttons</p>
              </div>
            </div>
            <div className="flex gap-2">
              <button
                onClick={shareToLinkedIn}
                className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors text-sm font-medium"
                title="Share on LinkedIn"
              >
                <Linkedin className="w-4 h-4" />
                <span className="hidden sm:inline">LinkedIn</span>
              </button>
              <button
                onClick={shareToTwitter}
                className="flex items-center gap-2 px-4 py-2 bg-sky-600 hover:bg-sky-700 text-white rounded-lg transition-colors text-sm font-medium"
                title="Share on Twitter/X"
              >
                <Twitter className="w-4 h-4" />
                <span className="hidden sm:inline">Twitter</span>
              </button>
              <button
                onClick={shareToFacebook}
                className="flex items-center gap-2 px-4 py-2 bg-blue-800 hover:bg-blue-900 text-white rounded-lg transition-colors text-sm font-medium"
                title="Share on Facebook"
              >
                <Facebook className="w-4 h-4" />
                <span className="hidden sm:inline">Facebook</span>
              </button>
              <button
                onClick={shareToInstagram}
                className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white rounded-lg transition-colors text-sm font-medium"
                title="Copy caption for Instagram"
              >
                <Instagram className="w-4 h-4" />
                <span className="hidden sm:inline">Instagram</span>
              </button>
            </div>
          </div>

          <div className="space-y-4">
            {data.linkedin_post && (
              <div className="bg-gray-800/50 rounded-lg p-4 border border-blue-500/20">
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center space-x-2">
                    <Linkedin className="w-5 h-5 text-blue-400" />
                    <span className="text-sm font-semibold text-blue-300">LinkedIn Post</span>
                  </div>
                  <button
                    onClick={() => copyToClipboard(data.linkedin_post!, 'linkedin')}
                    className="flex items-center space-x-1 px-3 py-1 bg-blue-500/20 hover:bg-blue-500/30 text-blue-300 rounded-lg text-xs transition-colors"
                  >
                    {copiedField === 'linkedin' ? (
                      <>
                        <Check className="w-3 h-3" />
                        <span>Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3 h-3" />
                        <span>Copy</span>
                      </>
                    )}
                  </button>
                </div>
                <p className="text-gray-300 text-sm leading-relaxed">{data.linkedin_post}</p>
              </div>
            )}

            {data.twitter_post && (
              <div className="bg-gray-800/50 rounded-lg p-4 border border-sky-500/20">
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center space-x-2">
                    <Twitter className="w-5 h-5 text-sky-400" />
                    <span className="text-sm font-semibold text-sky-300">Twitter Post</span>
                  </div>
                  <button
                    onClick={() => copyToClipboard(data.twitter_post!, 'twitter')}
                    className="flex items-center space-x-1 px-3 py-1 bg-sky-500/20 hover:bg-sky-500/30 text-sky-300 rounded-lg text-xs transition-colors"
                  >
                    {copiedField === 'twitter' ? (
                      <>
                        <Check className="w-3 h-3" />
                        <span>Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3 h-3" />
                        <span>Copy</span>
                      </>
                    )}
                  </button>
                </div>
                <p className="text-gray-300 text-sm leading-relaxed">{data.twitter_post}</p>
              </div>
            )}

            {data.instagram_caption && (
              <div className="bg-gray-800/50 rounded-lg p-4 border border-pink-500/20">
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center space-x-2">
                    <Instagram className="w-5 h-5 text-pink-400" />
                    <span className="text-sm font-semibold text-pink-300">Instagram Caption</span>
                  </div>
                  <button
                    onClick={() => copyToClipboard(data.instagram_caption!, 'instagram')}
                    className="flex items-center space-x-1 px-3 py-1 bg-pink-500/20 hover:bg-pink-500/30 text-pink-300 rounded-lg text-xs transition-colors"
                  >
                    {copiedField === 'instagram' ? (
                      <>
                        <Check className="w-3 h-3" />
                        <span>Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3 h-3" />
                        <span>Copy</span>
                      </>
                    )}
                  </button>
                </div>
                <p className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap">{data.instagram_caption}</p>
              </div>
            )}

            {data.facebook_post && (
              <div className="bg-gray-800/50 rounded-lg p-4 border border-blue-600/20">
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center space-x-2">
                    <Facebook className="w-5 h-5 text-blue-500" />
                    <span className="text-sm font-semibold text-blue-300">Facebook Post</span>
                  </div>
                  <button
                    onClick={() => copyToClipboard(data.facebook_post!, 'facebook')}
                    className="flex items-center space-x-1 px-3 py-1 bg-blue-600/20 hover:bg-blue-600/30 text-blue-300 rounded-lg text-xs transition-colors"
                  >
                    {copiedField === 'facebook' ? (
                      <>
                        <Check className="w-3 h-3" />
                        <span>Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3 h-3" />
                        <span>Copy</span>
                      </>
                    )}
                  </button>
                </div>
                <p className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap">{data.facebook_post}</p>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Source Summary Section */}
      <div className="bg-green-900/20 rounded-xl p-6 border border-green-500/30">
        <div className="flex items-center space-x-3 mb-4">
          <div className="w-10 h-10 bg-green-500/20 rounded-lg flex items-center justify-center">
            <FileText className="w-5 h-5 text-green-400" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-white">Source Summary</h3>
            <p className="text-sm text-gray-400">What the input URL is conveying</p>
          </div>
        </div>
        <div className="text-gray-300 leading-relaxed whitespace-pre-line">
          {data.meta_description || data.ai_summary || 'No summary available'}
        </div>
      </div>

      {/* Verified Origin / Moment of Truth */}
      {data.verified_origin && (
        <div className="bg-orange-900/20 rounded-xl p-6 border border-orange-500/30">
          <div className="flex items-center space-x-3 mb-4">
            <div className="w-10 h-10 bg-orange-500/20 rounded-lg flex items-center justify-center">
              <Clock className="w-5 h-5 text-orange-400" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">Verified Origin / Moment of Truth</h3>
              <p className="text-sm text-gray-400">Historical analysis and earliest mentions</p>
            </div>
          </div>
          <div className="space-y-3 text-gray-300 leading-relaxed whitespace-pre-line">
            {data.verified_origin}
          </div>
        </div>
      )}

      {/* Latest Updates & Future Forecast */}
      {data.future_forecast && (
        <div className="bg-blue-900/20 rounded-xl p-6 border border-blue-500/30">
          <div className="flex items-center space-x-3 mb-4">
            <div className="w-10 h-10 bg-blue-500/20 rounded-lg flex items-center justify-center">
              <TrendingUp className="w-5 h-5 text-blue-400" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">Latest Updates & Future Forecast</h3>
              <p className="text-sm text-gray-400">Current trends and future predictions</p>
            </div>
          </div>
          <div className="space-y-3 text-gray-300 leading-relaxed whitespace-pre-line">
            {data.future_forecast}
          </div>
        </div>
      )}

      {/* AI Summary */}
      {data.ai_summary && (
        <div className="bg-purple-900/20 rounded-xl p-6 border border-purple-500/30">
          <h3 className="text-lg font-bold text-white mb-3">AI Summary</h3>
          <p className="text-gray-300 leading-relaxed">{data.ai_summary}</p>
        </div>
      )}

      {/* Key Highlights */}
      {data.highlighted_content && data.highlighted_content.length > 0 && (
        <div className="bg-gray-800/30 rounded-xl p-6 border border-purple-500/20">
          <h3 className="text-lg font-bold text-white mb-4">Key Highlights</h3>
          <div className="space-y-3">
            {data.highlighted_content
              .map(item => ({
                ...item,
                text: cleanHighlightText(item.text)
              }))
              .filter(item => item.text.length > 0)
              .map((item, index) => (
                <div
                  key={index}
                  className="flex items-start space-x-3 p-3 bg-gray-900/50 rounded-lg border border-purple-500/20"
                >
                  <div className="flex-shrink-0 w-6 h-6 bg-purple-500/30 rounded-full flex items-center justify-center text-purple-300 text-xs font-bold">
                    {item.importance || index + 1}
                  </div>
                  <p className="text-gray-300 text-sm flex-1">{item.text}</p>
                </div>
              ))}
          </div>
          {data.highlighted_content.filter(item => cleanHighlightText(item.text).length > 0).length === 0 && (
            <p className="text-gray-500 text-sm text-center py-4">
              No key highlights extracted. Try different keywords or check the AI Summary section.
            </p>
          )}
        </div>
      )}

      {/* Open Graph Data */}
      {data.og_data && (
        <div className="bg-gray-800/30 rounded-xl p-6 border border-purple-500/20">
          <h3 className="text-lg font-bold text-white mb-4">Open Graph Data</h3>
          
          {data.og_data.image && (
            <div className="mb-4">
              <img
                src={data.og_data.image}
                alt={data.og_data.title || 'OG Image'}
                className="w-full h-48 object-cover rounded-lg"
                onError={(e) => {
                  e.currentTarget.style.display = 'none';
                }}
              />
            </div>
          )}

          <div className="space-y-2 text-sm">
            {data.og_data.title && (
              <div>
                <span className="text-purple-300 font-medium">OG Title: </span>
                <span className="text-gray-300">{data.og_data.title}</span>
              </div>
            )}
            {data.og_data.description && (
              <div>
                <span className="text-purple-300 font-medium">OG Description: </span>
                <span className="text-gray-300">{data.og_data.description}</span>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Links Found */}
      {data.links && data.links.length > 0 && (
        <div className="bg-gray-800/30 rounded-xl p-6 border border-purple-500/20">
          <h3 className="text-lg font-bold text-white mb-4">Links Found ({data.links.length})</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 max-h-64 overflow-y-auto">
            {data.links.slice(0, 20).map((link, index) => (
              <a
                key={index}
                href={link.url}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center space-x-2 p-3 bg-gray-900/50 rounded-lg hover:bg-gray-900/70 transition-colors border border-purple-500/10 hover:border-purple-500/30 group"
              >
                <ExternalLink className="w-4 h-4 text-purple-400 flex-shrink-0 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform" />
                <span className="text-sm text-gray-300 truncate">{link.text || link.url}</span>
                {link.type && (
                  <span className="text-xs text-purple-400 ml-auto">
                    {link.type}
                  </span>
                )}
              </a>
            ))}
          </div>
          {data.links.length > 20 && (
            <p className="text-sm text-gray-500 mt-3">
              Showing 20 of {data.links.length} links
            </p>
          )}
        </div>
      )}

      {/* Export Section */}
      <div className="bg-gray-800/30 rounded-xl p-6 border border-purple-500/20">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <h3 className="text-lg font-bold text-white mb-1 flex items-center gap-2">
              <Download className="w-5 h-5" />
              Export Analysis
            </h3>
            <p className="text-sm text-gray-400">Download this analysis in various formats</p>
          </div>
          <div className="flex gap-2 flex-wrap">
            <button
              onClick={() => exportAnalysis('txt')}
              className="px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded-lg transition-colors flex items-center gap-2 text-sm"
            >
              <File className="w-4 h-4" />
              .TXT
            </button>
            <button
              onClick={() => exportAnalysis('doc')}
              className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors flex items-center gap-2 text-sm"
            >
              <FileText className="w-4 h-4" />
              .DOC
            </button>
            <button
              onClick={() => exportAnalysis('pdf')}
              className="px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg transition-colors flex items-center gap-2 text-sm"
            >
              <Download className="w-4 h-4" />
              .PDF
            </button>
            <button
              onClick={() => exportAnalysisJSON()}
              className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg transition-colors flex items-center gap-2 text-sm font-semibold"
              title="Export structured JSON with social media posts"
            >
              <File className="w-4 h-4" />
              .JSON (Structured)
            </button>
          </div>
        </div>
      </div>

      {/* Timestamps */}
      {data.created_at && (
        <div className="text-center text-sm text-gray-500 pt-4 border-t border-gray-800">
          <div className="flex items-center justify-center gap-4">
            <span>Created: {new Date(data.created_at).toLocaleString()}</span>
            <span>•</span>
            <span>Completed: {new Date(data.created_at).toLocaleString()}</span>
          </div>
        </div>
      )}
    </div>
  );
}